Day1
maxum2120/SecondTry pull request #1
Opened 2022-01-21 22:32 UTC by maxum2120

2022-01-23 21:03 UTC, drfender requested changes

2022-01-23 21:03 UTC, drfender commented on index.html
> +            <!-- <input type="button" value="Download Resume" class="buttonInform"> -->
для чого цей комент?
видали?

2022-01-23 21:03 UTC, drfender commented on index.html
> +        <div class="inform">
будемо працювати по БЕМу
я розказував
block
block__element
block_modificator

2022-01-23 21:03 UTC, drfender commented on index.html
> +          <div class="text-inform">
так що тут 
.inform__texts

2022-01-23 21:03 UTC, drfender commented on index.html
> +            <button class="inform-button">Download Resume</button>
inform__button

2022-01-23 21:03 UTC, drfender commented on index.html
> +          <div class="photo-inform">
inform__photo

2022-01-23 21:03 UTC, drfender commented on index.html
> +        <div class="inform">
ну і не думаю, що назва inform коректне
можливо ліпше .info

2022-01-23 21:03 UTC, drfender commented on styles/style.css
> +	height: 200px;
а для чого ці обмеження контенту?

2022-01-23 21:03 UTC, drfender commented on styles/style.css
> +.photo {
тут таокж якісь специфічні обмеження

2022-01-23 21:04 UTC, drfender commented on index.html
> +        <div class="inform">
https://ru.bem.info/methodology/quick-start/ на почитать

2022-01-24 10:44 UTC, maxum2120 commented on index.html
> +            <!-- <input type="button" value="Download Resume" class="buttonInform"> -->
Для себе писав

2022-01-26 09:50 UTC, drfender approved these changes

2022-01-26 09:50 UTC, drfender commented on styles/style.css
> +	max-width: 808px;
треба буде винести в окремий клас в настпуній задачі

2022-01-26 10:45 UTC, merged